### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by luiztauffer**
add missing dependency for init-compute-resource-node

### CODE REVIEW

**Comment by luiztauffer** [comment]
@magland perhaps the `requirements.txt` in the root dir should be in the `/python` dir?

**Comment by magland** [comment]
@luiztauffer The requirements.txt in the root directory is meant to be for the vercel api deployment (vercel uses that). The dependencies for the python package (init-compute-resource-node) are in setup.py https://github.com/scratchrealm/protocaas/blob/main/python/setup.py

**Comment by luiztauffer** [comment]
I see, so this PR should be enough as it is, just missing one dependency there

**Comment by magland** [comment]
Merging. Thanks!

**Comment by luiztauffer** [comment]
@magland I do think this extra dependency on `setup.py` is needed. At least in my local installation in a clean environment, it complained the `cryptography` dependency was missing when running `protocaas init-compute-resource-node`

**Comment by magland** [comment]
Oops I meant to merge but closed instead. Merging now.

**Pull request merged**
